id: PE5FCCD8C
initial_creation_type: input
source_metadata:
  Title: आर्यश्री ग्रहमातृका नाम धारणी
  Editor: Ratna Bahadur Vajracharya
  Publisher: Mukta Raj Vajracharya
  Place of Publication: Na Tole, Lalipur, Nepal
  Year: N.S 1080
  आर्यश्री ग्रहमातृका नाम धारणी:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:22:17.343068'
last_modified_at: '2022-03-08T17:22:17.343075'
